-- Gamification + notification enum extensions

DO $$ BEGIN ALTER TYPE "XpAction" ADD VALUE IF NOT EXISTS 'SECTION_COMPLETE'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "XpAction" ADD VALUE IF NOT EXISTS 'TASK_COMPLETE'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "XpAction" ADD VALUE IF NOT EXISTS 'NOTE_CREATE'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "XpAction" ADD VALUE IF NOT EXISTS 'FINAL_TASK_SUBMIT'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "XpAction" ADD VALUE IF NOT EXISTS 'PEER_REVIEW_COMPLETE'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
